name: CI Maven Project

on: 
 workflow_dispatch:
  inputs:
    TARGET_ENVIRONMENT:
      description: "Target environment"
      type: choice
      options:
       - dev
       - qa
       - prod
      default: dev
      required: true

jobs: 
 CI_Non-conterization_build:
  runs-on: ubuntu-latest
  environment: dev
  steps: 
   - name: Checkout
     uses: actions/checkout@v4.2.2
   - name: Setup Java JDK
     uses: actions/setup-java@v3.14.1
     with:
      java-version: 17
      distribution: microsoft
   - name: Build using maven
     run: mvn --batch-mode --update-snapshots verify
   - run: mkdir staging && cp target/*.jar staging 
   - name: Upload a Build Artifact
     uses: actions/upload-artifact@v4.6.2
     with: 
      name: Package
      path: staging
 build_qa:
   needs: CI_Non-conterization_build
   runs-on: ubuntu-latest
   environment: qa
   steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
     - name: Print Environment
       run: echo "Deploying to QA environment"
     - name: Run QA Tests
       run: mvn test
 build_prod:
   needs: build_qa
   runs-on: ubuntu-latest
   environment: qa
   steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
     - name: Print Environment
       run: echo "Deploying to PROD environment"
     - name: Deploy
       run: echo "Deployment to PROD completed successfully"
   
      
